### ISSUE TITLE
How to do the live stream?

### ISSUE THREAD

**Issue by ytwytw** [kwirk/yidashcam#2]
I try to use VLC to open `rtsp://192.168.1.254/xxx.mov` but it doesnt work

I did use `python3 -m yidashcam stream` to activate the stream

Can you advise?

Thanks

**Comment by andyzasl** [comment]
why you use "python python3"  ?
1 single "python3" should be enough

**Comment by ytwytw** [comment]
Type error 😷

**Comment by kwirk** [comment]
Do you get an error message in VLC?

**Comment by ytwytw** [comment]
@kwirk Yes

**Comment by kwirk** [comment]
What error message(s) do you get? What firmware version is your dash cam?

**Comment by tedgonzo** [comment]
I have the same issue with the stream command:
`~ $ python -m yidashcam stream
Connect to video stream at: rtsp://192.168.1.254/xxx.mov
Press enter to take video photo, or Ctrl-C to exit
`
While trying to open stream in VLC i get the following message:
`main debug: processing request item: rtsp://192.168.1.254/xxx.mov, node: Play list, skip: 0
main debug: resyncing on rtsp://192.168.1.254/xxx.mov
main debug: rtsp://192.168.1.254/xxx.mov is at 0
main debug: starting playback of new item
main debug: resyncing on rtsp://192.168.1.254/xxx.mov
main debug: rtsp://192.168.1.254/xxx.mov is at 0
main debug: creating new input thread
main debug: Creating an input for 'rtsp://192.168.1.254/xxx.mov'
main debug: requesting art for new input thread
main debug: using timeshift granularity of 50 MiB
main debug: using default timeshift path
main debug: looking for meta fetcher module matching "any": 0 candidates
main debug: no meta fetcher modules
main debug: `rtsp://192.168.1.254/xxx.mov' gives access `rtsp' demux `any' path `192.168.1.254/xxx.mov'
main debug: looking for art finder module matching "any": 1 candidates
main debug: creating demux: access='rtsp' demux='any' location='192.168.1.254/xxx.mov' file='(null)'
main debug: no art finder modules matched
main debug: looking for access_demux module matching "rtsp": 11 candidates
main debug: no access_demux modules matched
main debug: creating access: rtsp://192.168.1.254/xxx.mov
main debug: looking for access module matching "rtsp": 21 candidates
satip debug: try to open 'rtsp://192.168.1.254/xxx.mov'
satip debug: connect to host '192.168.1.254'
main debug: net: connecting to 192.168.1.254 port 554
main debug: looking for meta fetcher module matching "any": 0 candidates
main debug: no meta fetcher modules
main debug: looking for art finder module matching "any": 1 candidates
main debug: no art finder modules matched
qt debug: IM: Setting an input
main debug: connection succeeded (socket = 28)
main debug: net: opening 0.0.0.0 datagram port 9310
main debug: net: opening 0.0.0.0 datagram port 9311
satip error: Failed to setup RTSP session
main debug: no access modules matched
main debug: dead input
main debug: changing item without a request (current 0/1)
main debug: nothing to play
qt debug: IM: Deleting the input`

Cam firmware is 1.03.033-US

**Comment by tedgonzo** [comment]
I have the same issue with the stream command:
`~ $ python -m yidashcam stream
Connect to video stream at: rtsp://192.168.1.254/xxx.mov
Press enter to take video photo, or Ctrl-C to exit
`
While trying to open stream in VLC i get the following message:
`
main debug: processing request item: rtsp://192.168.1.254/xxx.mov, node: Lista odtwarzania, skip: 0
main debug: resyncing on rtsp://192.168.1.254/xxx.mov
main debug: rtsp://192.168.1.254/xxx.mov is at 0
main debug: starting playback of new item
main debug: resyncing on rtsp://192.168.1.254/xxx.mov
main debug: rtsp://192.168.1.254/xxx.mov is at 0
main debug: creating new input thread
main debug: Creating an input for 'rtsp://192.168.1.254/xxx.mov'
main debug: requesting art for new input thread
main debug: using timeshift granularity of 50 MiB
main debug: using default timeshift path
main debug: looking for meta fetcher module matching "any": 0 candidates
main debug: no meta fetcher modules
main debug: `rtsp://192.168.1.254/xxx.mov' gives access `rtsp' demux `any' path `192.168.1.254/xxx.mov'
main debug: looking for art finder module matching "any": 1 candidates
main debug: creating demux: access='rtsp' demux='any' location='192.168.1.254/xxx.mov' file='(null)'
main debug: no art finder modules matched
main debug: looking for access_demux module matching "rtsp": 11 candidates
main debug: no access_demux modules matched
main debug: creating access: rtsp://192.168.1.254/xxx.mov
main debug: looking for access module matching "rtsp": 21 candidates
satip debug: try to open 'rtsp://192.168.1.254/xxx.mov'
satip debug: connect to host '192.168.1.254'
main debug: net: connecting to 192.168.1.254 port 554
main debug: looking for meta fetcher module matching "any": 0 candidates
main debug: no meta fetcher modules
main debug: looking for art finder module matching "any": 1 candidates
main debug: no art finder modules matched
qt debug: IM: Setting an input
main debug: connection succeeded (socket = 28)
main debug: net: opening 0.0.0.0 datagram port 9310
main debug: net: opening 0.0.0.0 datagram port 9311
satip error: Failed to setup RTSP session
main debug: no access modules matched
main debug: dead input
main debug: changing item without a request (current 0/1)
main debug: nothing to play
qt debug: IM: Deleting the input
`

Cam firmware is 1.03.033-US

**Comment by tedgonzo** [comment]
I have the same issue with the stream command:
`~ $ python -m yidashcam stream
Connect to video stream at: rtsp://192.168.1.254/xxx.mov
Press enter to take video photo, or Ctrl-C to exit
`
While trying to open stream in VLC i get the following message:

> main debug: processing request item: rtsp://192.168.1.254/xxx.mov, node: Lista odtwarzania, skip: 0
> main debug: resyncing on rtsp://192.168.1.254/xxx.mov
> main debug: rtsp://192.168.1.254/xxx.mov is at 0
> main debug: starting playback of new item
> main debug: resyncing on rtsp://192.168.1.254/xxx.mov
> main debug: rtsp://192.168.1.254/xxx.mov is at 0
> main debug: creating new input thread
> main debug: Creating an input for 'rtsp://192.168.1.254/xxx.mov'
> main debug: requesting art for new input thread
> main debug: using timeshift granularity of 50 MiB
> main debug: using default timeshift path
> main debug: looking for meta fetcher module matching "any": 0 candidates
> main debug: no meta fetcher modules
> main debug: `rtsp://192.168.1.254/xxx.mov' gives access `rtsp' demux `any' path `192.168.1.254/xxx.mov'
> main debug: looking for art finder module matching "any": 1 candidates
> main debug: creating demux: access='rtsp' demux='any' location='192.168.1.254/xxx.mov' file='(null)'
> main debug: no art finder modules matched
> main debug: looking for access_demux module matching "rtsp": 11 candidates
> main debug: no access_demux modules matched
> main debug: creating access: rtsp://192.168.1.254/xxx.mov
> main debug: looking for access module matching "rtsp": 21 candidates
> satip debug: try to open 'rtsp://192.168.1.254/xxx.mov'
> satip debug: connect to host '192.168.1.254'
> main debug: net: connecting to 192.168.1.254 port 554
> main debug: looking for meta fetcher module matching "any": 0 candidates
> main debug: no meta fetcher modules
> main debug: looking for art finder module matching "any": 1 candidates
> main debug: no art finder modules matched
> qt debug: IM: Setting an input
> main debug: connection succeeded (socket = 28)
> main debug: net: opening 0.0.0.0 datagram port 9310
> main debug: net: opening 0.0.0.0 datagram port 9311
> satip error: Failed to setup RTSP session
> main debug: no access modules matched
> main debug: dead input
> main debug: changing item without a request (current 0/1)
> main debug: nothing to play
> qt debug: IM: Deleting the input


Cam firmware is 1.03.033-US

**Comment by tedgonzo** [comment]
I have the same issue with the stream command:
`~ $ python -m yidashcam stream
Connect to video stream at: rtsp://192.168.1.254/xxx.mov
Press enter to take video photo, or Ctrl-C to exit
`
While trying to open stream in VLC i get the following message:

> main debug: processing request item: rtsp://192.168.1.254/xxx.mov, node: Lista odtwarzania, skip: 0
> main debug: resyncing on rtsp://192.168.1.254/xxx.mov
> main debug: rtsp://192.168.1.254/xxx.mov is at 0
> main debug: starting playback of new item
> main debug: resyncing on rtsp://192.168.1.254/xxx.mov
> main debug: rtsp://192.168.1.254/xxx.mov is at 0
> main debug: creating new input thread
> main debug: Creating an input for 'rtsp://192.168.1.254/xxx.mov'
> main debug: requesting art for new input thread
> main debug: using timeshift granularity of 50 MiB
> main debug: using default timeshift path
> main debug: looking for meta fetcher module matching "any": 0 candidates
> main debug: no meta fetcher modules
> main debug: `rtsp://192.168.1.254/xxx.mov' gives access `rtsp' demux `any' path `192.168.1.254/xxx.mov'
> main debug: looking for art finder module matching "any": 1 candidates
> main debug: creating demux: access='rtsp' demux='any' location='192.168.1.254/xxx.mov' file='(null)'
> main debug: no art finder modules matched
> main debug: looking for access_demux module matching "rtsp": 11 candidates
> main debug: no access_demux modules matched
> main debug: creating access: rtsp://192.168.1.254/xxx.mov
> main debug: looking for access module matching "rtsp": 21 candidates
> satip debug: try to open 'rtsp://192.168.1.254/xxx.mov'
> satip debug: connect to host '192.168.1.254'
> main debug: net: connecting to 192.168.1.254 port 554
> main debug: looking for meta fetcher module matching "any": 0 candidates
> main debug: no meta fetcher modules
> main debug: looking for art finder module matching "any": 1 candidates
> main debug: no art finder modules matched
> qt debug: IM: Setting an input
> main debug: connection succeeded (socket = 28)
> main debug: net: opening 0.0.0.0 datagram port 9310
> main debug: net: opening 0.0.0.0 datagram port 9311
> satip error: Failed to setup RTSP session
> main debug: no access modules matched
> main debug: dead input
> main debug: changing item without a request (current 0/1)
> main debug: nothing to play
> qt debug: IM: Deleting the input

Cam firmware is 1.03.033-US. Here is the nmap output without yidashcam stream off and on:
> ~ $ nmap 192.168.1.254
> Starting Nmap 7.70 ( https://nmap.org ) at 2018-12-26 18:21 CET
> Nmap scan report for 192.168.1.254
> Host is up (0.033s latency).
> Not shown: 998 closed ports
> PORT     STATE SERVICE
> 80/tcp   open  http
> 3333/tcp open  dec-notes
> 
> Nmap done: 1 IP address (1 host up) scanned in 0.56 seconds

> ~ $ nmap 192.168.1.254
> Starting Nmap 7.70 ( https://nmap.org ) at 2018-12-26 18:21 CET
> Nmap scan report for 192.168.1.254
> Host is up (0.028s latency).
> Not shown: 996 closed ports
> PORT     STATE SERVICE
> 80/tcp   open  http
> 554/tcp  open  rtsp
> 3333/tcp open  dec-notes
> 8000/tcp open  http-alt
> 
> Nmap done: 1 IP address (1 host up) scanned in 1.53 seconds
